### ISSUE TITLE
Updating create-graphql breaks other projects

### ISSUE THREAD

**Issue by idkjs** [graphql-community/create-graphql#102]
running `yarn global upgrade create-graphql` to update. Then running a project that was created with it and you get this. Seems odd because you would think that create-graphql gets out of the way after you have generated your file. If you rm -rf node modules, yarn install, it works. 

Any idea why its doing this?

```sh
### Current Behavior
 …/CODE/relay-mm  ⬢ 6.9.2  b591a2fd yelpnine ●  npm run watch

> graphql-dataloader-boilerplate@0.0.1 watch /Users/devworx/CODE/relay-mm
> nodemon src/index.js --exec babel-node

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/index.js`
/Users/devworx/CODE/relay-mm/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/devworx/CODE/relay-mm/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/devworx/CODE/relay-mm/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/devworx/CODE/relay-mm/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
[nodemon] app crashed - waiting for file changes before starting...
^C
 …/CODE/relay-mm  ⬢ 6.9.2  b591a2fd yelpnine ●  rm -rf node_modules
 …/CODE/relay-mm  ⬢ 6.9.2  b591a2fd yelpnine ●  yarn       ✓  5390  18:24:01
yarn install v0.24.6
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "koa-graphql-batch@1.1.0" has incorrect peer dependency "graphql@^0.8.2".
warning "eslint-config-airbnb@14.1.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^3.0.2 || ^4.0.0".
warning "eslint-config-airbnb@14.1.0" has unmet peer dependency "eslint-plugin-react@^6.9.0".
[4/4] 📃  Building fresh packages...
✨  Done in 73.59s.
 …/CODE/relay-mm  ⬢ 6.9.2  b591a2fd yelpnine ●  npm run watch

> graphql-dataloader-boilerplate@0.0.1 watch /Users/devworx/CODE/relay-mm
> nodemon src/index.js --exec babel-node

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/index.js`
Connected to localhost:27017/yelpnine
Server started on port 5000### Expected Behavior
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->
```
### Your Environment

| software         | version
| ---------------- | -------
| create-graphql   |  1.1.17
| node             | 8.1.2
| npm or yarn      | yarn
| macOS| Sierra

**Comment by sibelius** [comment]
this happens when you do `npm install` using a node version

and try to run the code with another node version
